# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informall', '0002_auto_20170225_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informall.State'),
        ),
    ]
