# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informall', '0003_news_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='institution_type',
            field=models.CharField(choices=[(b'public', b'public'), (b'academic', b'academic'), (b'private', b'private')], default=b'public', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='permissions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='website',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
