# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informall', '0004_auto_20170226_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
