# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informall', '0005_auto_20170226_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='website',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
